name: Microblog CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Create Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Set environment variables
      run: |
        export FLASK_APP=microblog.py
        export FLASK_ENV=development
        
    - name: Initialize database
      run: |
        flask db upgrade
        
    - name: Run the app
      run: |
        flask run &
        sleep 10
        
    - name: Run tests
      run: |
        pip install pytest
        pytest tests.py
        
    - name: Teardown
      run: |
        pkill flask
